name: Leihatia
favicon: null
layout_spectrum: 0.56818
typography_spectrum: 0.24895
title: LeiHatia Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835155-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
