name: Leihatia
favicon: null
layout_spectrum: 0.606705158483237
typography_spectrum: 0.5873006673064083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8204237355384976
  lightness: 0.6858321414329112
  saturation: 0.2456327322870493
  rhythmicContrast: 0.4187850982416421
purpose: []
